receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        cors:
          # noinspection HttpUrlsUsage
          allowed_origins:
            - http://*
            - https://*
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_max_size: 50
    send_batch_size: 50
    timeout: 2s

  memory_limiter:
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 20

  resourcedetection:
    detectors: [ gcp ]
    timeout: 10s

exporters:
  googlecloud:
    sending_queue:
      enabled: true
  googlemanagedprometheus:

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions:
    - health_check
  pipelines:
    metrics/otlp:
      receivers:
        - otlp
      processors:
        - resourcedetection
        - memory_limiter
        - batch
      exporters:
        - googlecloud
    traces:
      receivers:
        - otlp
      processors:
        - resourcedetection
        - memory_limiter
        - batch
      exporters:
        - googlecloud
  telemetry:
    logs:
      encoding: json
