receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        cors:
          # noinspection HttpUrlsUsage
          allowed_origins:
            - http://*
            - https://*
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_max_size: 200
    send_batch_size: 200
    timeout: 5s

  memory_limiter:
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 20

  resourcedetection:
    detectors: [ gcp ]
    timeout: 10s

  transform/collision:
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["exported_location"], attributes["location"])
          - delete_key(attributes, "location")
          - set(attributes["exported_cluster"], attributes["cluster"])
          - delete_key(attributes, "cluster")
          - set(attributes["exported_namespace"], attributes["namespace"])
          - delete_key(attributes, "namespace")
          - set(attributes["exported_job"], attributes["job"])
          - delete_key(attributes, "job")
          - set(attributes["exported_instance"], attributes["instance"])
          - delete_key(attributes, "instance")
          - set(attributes["exported_project_id"], attributes["project_id"])
          - delete_key(attributes, "project_id")

exporters:
  googlecloud:
    log:
      default_log_name: opentelemetry-collector
  googlemanagedprometheus:

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions:
    - health_check
  pipelines:
    metrics/otlp:
      receivers:
        - otlp
      processors:
        - resourcedetection
        - transform/collision
        - memory_limiter
        - batch
      exporters:
        - googlemanagedprometheus
    traces:
      receivers:
        - otlp
      processors:
        - resourcedetection
        - memory_limiter
        - batch
      exporters:
        - googlecloud
#        - debug
